name: Update Local README

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      # (Optional) Checkout source or template repo
      - name: Checkout source README
        uses: actions/checkout@v4
        with:
          repository: yourusername/source-repo  # Use your actual source if needed
          path: source_readme

      # Transform README.md
      - name: Update README content
        run: |
          # Your processing commands here
          # For example:
          # REPO="${GITHUB_REPOSITORY##*/}"
          # SECTION=$(awk '/<!-- buttons -->/{flag=1;next}/<!-- endbuttons -->/{flag=0}flag' source_readme/README.md)
          # SECTION_UPDATED=$(echo "$SECTION" | sed "s/\.github/$REPO/g")
          # awk ... # update target README logic here

      # Save new README locally without push
      - name: Upload updated README as artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-readme
          path: README.md
