name: Update README

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # Daily at 4 AM UTC

jobs:
  update-readme-buttons:
    runs-on: ubuntu-latest
    env:
      SOURCE_REPO: ivancarlosti/.github
      SOURCE_BRANCH: main

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Checkout source README
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPO }}
          ref: ${{ env.SOURCE_BRANCH }}
          path: source_readme

      - name: Update README.md buttons section
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          SECTION=$(awk '/<!-- buttons -->/{flag=1;next}/<!-- endbuttons -->/{flag=0}flag' source_readme/README.md)
          SECTION_UPDATED=$(echo "$SECTION" | sed "s/\.github/$REPO_NAME/g")
          awk -v new_section="$SECTION_UPDATED" '
            BEGIN { skip=0 }
            /<!-- buttons -->/ {
              print
              print new_section
              skip=1
              next
            }
            /<!-- endbuttons -->/ && skip {
              print
              skip=0
              next
            }
            !skip { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Remove source_readme from git index
        run: git rm --cached -r source_readme || true

      - name: Commit and push updated README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: README.md
          commit_message: "chore: sync README buttons from template"
          branch: ${{ github.ref_name }}
