name: Update README Buttons

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      SOURCE_REPO: ivancarlosti/.github
      SOURCE_BRANCH: main

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout source README template
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPO }}
          ref: ${{ env.SOURCE_BRANCH }}
          path: source_readme

      - name: Replace buttons section in README.md
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"

          # Extract section between markers from the source template
          SECTION=$(awk '/<!-- buttons -->/{flag=1;next}/<!-- endbuttons -->/{flag=0}flag' source_readme/README.md)

          # Replace ".github" with the current repository name
          SECTION_UPDATED=$(echo "$SECTION" | sed "s/\.github/${REPO_NAME}/g")

          # Replace section in the local README.md
          awk -v new_section="$SECTION_UPDATED" '
          BEGIN { skip=0 }
          /<!-- buttons -->/ {
            print
            print new_section
            skip=1
            next
          }
          /<!-- endbuttons -->/ && skip {
            print
            skip=0
            next
          }
          !skip { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Upload updated README.md as artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-readme
          path: README.md
