name: Update README Buttons

on:
  workflow_dispatch: # Manual triggering
  schedule:
    - cron: '0 4 * * *' # Daily at 4 AM UTC

jobs:
  update-readme-buttons:
    runs-on: ubuntu-latest
    env:
      SOURCE_REPO: ivancarlosti/.github # Change to your source repo
      SOURCE_BRANCH: main              # Change if source uses a different branch

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SOURCE_REPO }}
          ref: ${{ env.SOURCE_BRANCH }}
          path: source_readme

      - name: Extract and update button section
        id: update
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          # Extract section from source README
          SECTION=$(awk '/<!-- buttons -->/{flag=1;next}/<!-- endbuttons -->/{flag=0}flag' source_readme/README.md)
          # Replace .github with target repo's name
          SECTION_UPDATED=$(echo "$SECTION" | sed "s/\.github/${REPO_NAME}/g")
          
          # Replace section in target README.md
          awk -v new_section="$SECTION_UPDATED" '
            BEGIN {printed=0}
            /<!-- buttons -->/ {
              print; print new_section; skip=1; printed=1; next
            }
            /<!-- endbuttons -->/ && skip {
              skip=0; next
            }
            !skip { print }
            END { if (!printed) print "<!-- buttons -->\n" new_section "\n<!-- endbuttons -->" }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync README buttons from source"
          branch: ${{ github.ref_name }}
          
      # Optional: Open a PR instead of direct push
      # See actions like peter-evans/create-pull-request for PR workflow

